name: Build and Deploy Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # These permissions are required so that the Azure login action can request an ID token.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install Project Dependencies
        working-directory: ./email-function
        run: npm install

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Publish Azure Function App
        working-directory: ./email-function
        run: func azure functionapp publish sendEmailToSebas
        env:
          AZURE_WEBJOBS_STORAGE: ${{ secrets.AZURE_WEBJOBS_STORAGE }}
          FUNCTIONS_WORKER_RUNTIME: node
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
